# If you need help with YAML syntax, here are some quick references for you:
# https://learn-the-web.algonquindesign.ca/topics/markdown-yaml-cheat-sheet/#yaml
# https://learnxinyminutes.com/docs/yaml/
#
# Site settings
# These are used to personalize your new site. If you look in the HTML files,
# you will see them accessed via {{ site.title }}, {{ site.email }}, and so on.
# You can create any custom variable you would like, and they will be accessible
# in the templates via {{ site.myvariable }}.

title: Ryan J. Gallagher
email: gallagher.r@northeastern.edu
description: >- # this means to ignore newlines until "baseurl:"
  Network science PhD student mapping online communication networks
baseurl: "" # the subpath of your site, e.g. /blog
url: "localhost:4000"
#url: "https://ryanjgallagher.github.io/"
twitter_username: ryanjgallag
github_username:  ryanjgallagher

# Build settings
#theme: minima
#theme: bulma-clean-theme
remote_theme: chrisrhymes/bulma-clean-theme

# Turns publications into special pages
collections:
  publications:
    output: true
    layout: product
    image: https://via.placeholder.com/800x600
    show_sidebar: false

#remote_theme: chrisrhymes/bulma-clean-theme
plugins:
  - jekyll-feed

# Exclude from processing.
# The following items will not be processed, by default.
# Any item listed under the `exclude:` key here will be automatically added to
# the internal "default list".
#
# Excluded items can be processed by explicitly listing the directories or
# their entries' file path in the `include:` list.
#
# exclude:
#   - .sass-cache/
#   - .jekyll-cache/
#   - gemfiles/
#   - Gemfile
#   - Gemfile.lock
#   - node_modules/
#   - vendor/bundle/
#   - vendor/cache/
#   - vendor/gems/
#   - vendor/ruby/
